### PR TITLE
Fix duplicate symbol error when linking

### PR DESCRIPTION
**Pull request by mattgreen**
When running specific specs, it was possible for a single spec to be compiled twice, and then linked. The linker would choke on this, claiming a duplicate symbol. This pull fixes that bug by expanding the filename for each path before passing it to the rake spec task.

This was triggered by an incorrect `Guardfile` template included with `guard-motion`. The template was updated, as well as the README. The latter two fixes are not strictly necessary, but are included for completeness.

### CODE REVIEW

**Comment by mattgreen** [comment]
Also, I'm pretty sure the changelog/version bump commit is a GitHub bug.

**Comment by mordaroso** [comment]
We could add a separate class that does the cleanup like guard-rspec does in the [Inspector](https://github.com/guard/guard-rspec/blob/master/lib/guard/rspec/inspector.rb).
I think we need more cleanup anyway. For example for deleted/renamed files and the `keep_failed` feature.

What do you think?

**Comment by mattgreen** [comment]
Sounds good. I'll try to get to this tomorrow or Friday.

**Comment by mordaroso** [comment]
Hi @mattgreen 
I've [added an Inspector class](https://github.com/mordaroso/guard-motion/commit/3d025634a307cae366fa8cc5b1b92bb15082e67a) myself now. Does this solve your problem too?

**Comment by mattgreen** [comment]
Looks like it! Thank you!

**Pull request closed without merging**
